version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: quizcms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    container_name: quizcms-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  mongo_data:
